# Generated by Django 3.1 on 2020-08-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200807_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='price',
        ),
    ]
